# 自定义层

In [2]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

将层作为组件合并到更为复杂的模型中

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(3.4925e-10, grad_fn=<MeanBackward0>)

带参数的图层

In [4]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.9613, -0.0739, -0.8650],
        [ 2.3774, -0.7808, -0.4352],
        [ 0.4664, -1.2717, -2.7288],
        [ 1.6188,  1.5535, -0.8508],
        [ 0.4836,  0.2692, -1.4509]], requires_grad=True)

In [5]:
linear(torch.rand(2, 5))

tensor([[2.4899, 0.0000, 0.0000],
        [3.7475, 0.0000, 0.0000]])